### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by BenoityipMSFT** [SQLPlayer/azure.synapse.tools#1]
Json file is below
[Synapse.zip](https://github.com/SQLPlayer/azure.synapse.tools/files/7418409/Synapse.zip)

Error is below
![image](https://user-images.githubusercontent.com/90560187/138886201-2b6e889c-2a98-4882-8a6a-c30d34ed9945.png)

**Comment by NowinskiK** [comment]
All these bugs should be fixed in ver.0.16
