### ISSUE TITLE
Deployment of pipeline which reference Notebook fails

### ISSUE THREAD

**Issue by lidroz** [SQLPlayer/azure.synapse.tools#13]
I have a simple pipeline with one activity of type Notebook that reference a Spark notebook. When deploying this pipeline I get error message:
ASWT0014: Type [Notebook] is not supported.

Pipeline definition:
`{
	"name": "pl_execute_notebook_cicd",
	"properties": {
		"description": "Pipeline to trigger from Azure DevOps release to execute deployed Spark notebook dynamically",
		"activities": [
			{
				"name": "execute_notebook",
				"type": "SynapseNotebook",
				"dependsOn": [],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"notebook": {
						"referenceName": "generate_job_pipeline",
						"type": "NotebookReference"
					},
					"snapshot": true,
					"sparkPool": {
						"referenceName": "labsparkpool01",
						"type": "BigDataPoolReference"
					}
				}
			}
		],
		"parameters": {
			"notebook_name": {
				"type": "string"
			},
			"sparkpool_name": {
				"type": "string"
			}
		},
		"folder": {
			"name": "Lakehouse/Maintenance"
		},
		"annotations": []
	}
}`

Same pipeline had dynamic reference to Notebook from pipeline parameter:
`"typeProperties": {
					"notebook": {
						"referenceName": {
							"value": "@pipeline().parameters.notebook_name",
							"type": "Expression"
						},
						"type": "NotebookReference"
					},
					"snapshot": true,
					"sparkPool": {
						"referenceName": {
							"value": "@pipeline().parameters.sparkpool_name",
							"type": "Expression"
						},
						"type": "BigDataPoolReference"
					}
				}`

With dynamic reference to Notebook I got another error message:
ASWT0029: Unknown object type: parameters.

Desired behaviour is to ignore reference if it is set by Expression.

**Comment by NowinskiK** [comment]
Thanks for raising this issue. It's fixed now in version 0.21.
