### ISSUE TITLE
DevOps Extension

### ISSUE THREAD

**Issue by LiquoriChris** [SQLPlayer/azure.synapse.tools#14]
Hello @NowinskiK,

This is not really an issue but more of a question related to the synapse module. Are you planning on developing an Azure DevOps task similar to the Data Factory tasks. We currently use them and it is awesome! Just curious if any plans about Synapse. 

Thanks again,
Chris

**Comment by NowinskiK** [comment]
Hello Chris.
Thanks for your kind words.
No, for now, there are no plans to deploy this tool as Azure DevOps task(s).
You can use it as PS module which is still in a preview edition.
Microsoft has its own extension this time, so I can't see a good reason for that.

More details in this thread: 
[Question: Synapse](https://github.com/SQLPlayer/azure.datafactory.tools/issues/91)

**Comment by mzhukovs** [comment]
Given MS has its own official deployment task now, you could perhaps consider splitting out the diagramming functionality you have built (I was actually considering doing this myself but then I stumbled upon your great work) as a separate task which outputs the diagram as an artifact @NowinskiK
