### ISSUE TITLE
Mermaid diagram plugin in VS Code expects three backticks instead of three colons

### ISSUE THREAD

**Issue by reitse** [SQLPlayer/azure.synapse.tools#16]
I've tried out this tool this morning and it give's a nice overview of the mess I've made 😄 

The only thing is, I've added the Markdown Preview Mermaid Support pluging and found that your code starts with ::: mermaid. But I've found that, to show the diagram instead of the code, I needed ``` at the beginning of the file.

When I googled on Mermaid markdown, I found a lot of back ticks and not so many colons.

**Comment by NowinskiK** [comment]
Hi @reitse!
Thanks for looking at the tool.
The VSC plugin actually supports both ::: and ```.
The problem appears between GitHub and Azure DevOps - one supports ::: and the other one ``` only.

The following table shows the current state:

  | ::: | ```
-- | -- | --
GitHub - MD files | No | Yes
GitHub - issue/comments | No | Yes
Azure DevOps - MD files (Wiki) | Yes | No
Azure DevOps - work items | No | No
VS Code + MD Preview Mermaid Support | Yes | Yes

Thanks for your comment and as you can see - it doesn't make sense to change anything. 
If individual needs - can change it manually depends on target platform.

**Comment by reitse** [comment]
Hi Kamil,

Thanks for the quick reply!
Good explanation and, my VS code all of a sudden works with both as well.
Maybe something didn't stick the first time around.

In any case, thank you so much for this tool, it provides a lot of insight.

Met vriendelijke groet,

Reitse Eskens
