### ISSUE TITLE
Stopping a trigger gives an error

### ISSUE THREAD

**Issue by FrenkLoonen** [SQLPlayer/azure.synapse.tools#3]
STEP: Stopping triggers...
Getting triggers...
##[error]Unable to find type [Microsoft.Azure.Commands.Synapse.Models.PSTrigger].

Using Az.Synapse 0.19.0

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.synapse.models?view=az-ps-latest

**Comment by NowinskiK** [comment]
Are you able and keen to contribute to fix it?

**Comment by NowinskiK** [comment]
This should be fixed by version 0.16, please check out.
